



###
GET http://localhost:3000/api/collaborator/d8cbd074-293f-4be8-a7f5-ee0858aa8f5e/vacationrequests/


###
GET http://localhost:3000/api/collaborator/


###
POST http://localhost:3000/api/collaborator/
Content-Type: application/json

{
  "register": "9999",
  "name": "Jandira",
  "birthday": "1990-01-01",
  "hiringdate": "2021-01-01"
}


###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "login": "caliton",
    "password": "123"
}

###
GET http://localhost:3000/api/test-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU1MjM0YzJkLTlhZDAtNDQyNi04MTk1LTBhZDJmMTk1MmY1NiIsIm5hbWUiOiJDYWxpdG9uIE1hcmNvcyBHb27Dp2FsdmVzIEp1bmlvciIsInVzZXJuYW1lIjoiY2FsaXRvbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYzNjUwNjUzMywiZXhwIjoxNjM2NTA2NTYzfQ.BHVY3_tiALxRJzUnrPJSz5_gSZUux32siokdTlsalPk



###
GET http://localhost:3000/api/profile

###
GET http://localhost:3000/api/role


###
GET http://localhost:3000/api/profile

###
GET http://localhost:3000/api/user



POST http://localhost:3000/api/collaborator
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkNhbGl0b24iLCJ1c2VybmFtZSI6ImNhbGl0b24iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MzU3ODY4OTAsImV4cCI6MTYzNTc4NjkyMH0.yefywkQnVXF2M_Hwq6wpqrKAvcMsYdXhN4c7DoJcev8
Content-Type: application/json

{
    "name": "Caliton",
    "email": "caliton@mail.com",
    "register": "123.456.789",
    "birthday": "1996-06-03",
    "hiringdate": "2018-10-01",
    "departament": "76f54ee2-6e65-4ad8-89e4-1b0c79c77ef0",
    "profile": "d7a21b23-a62e-4cd4-997b-4eca51096368",
    "role": "2c9afceb-fd60-4330-9a90-0c3363003296"
}



###
GET http://localhost:3000/api/globalsettings


###
POST http://localhost:3000/api/collaborator/bulk/

Content-Type: application/json

{
    "data": [
  {
    "register": "1234",
    "name": "Andre Vasconcelos Souto",
    "hiringdate": "2000-01-01",
    "birthday": "2018-10-01"
  },
  {
    "register": "1235",
    "name": "Angelica Lucio Fidale Sampaio",
    "hiringdate": "2000-01-02",
    "birthday": "2010-12-31"
  },
  {
    "register": "1236",
    "name": "Anna Paula Graboski Correia Lima",
    "hiringdate": "2000-01-03",
    "birthday": "2010-01-03"
  },
  {
    "register": "1237",
    "name": "Antonio Carlos Neto",
    "hiringdate": "2000-01-04",
    "birthday": "2019-08-01"
  },
  {
    "register": "1238",
    "name": "Bruno Alberto de Oliveira",
    "hiringdate": "2000-01-05",
    "birthday": "2010-01-05"
  },
  {
    "register": "1240",
    "name": "Caio Cezar Queiroz",
    "hiringdate": "2000-01-07",
    "birthday": "2010-01-07"
  },
  {
    "register": "1208",
    "name": "Caliton Marcos Gonçalves Junior",
    "hiringdate": "1996-06-03",
    "birthday": "2019-10-01"
  }
]
}