export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PERSON_REPOSITORY = 'PERSON_REPOSITORY'
export const VACATION_TIME_REPOSITORY = 'VACATION_TIME_REPOSITORY'
export const VACATION_REQUEST_REPOSITORY = 'VACATION_REQUEST_REPOSITORY'